spring:
  application:
    name: microbank-customer-service
  config:
    import: configserver:http://localhost:8888
server:
  port: 6010
  servlet:
    context-path: /customer
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
customer:
  request:
    base: /
    authorize: /authorize
  mongodb:
    host: freecluster-s3rjf.mongodb.net
    user: AtlasAdmin
    db: microbank