# Use docker-compose up to run all MicroBank services.

version: "3.9"
services:
  microbank-angular:
    image: zacharyed/microbank-angular
    ports:
      - "443:443"
      - "80:80"
  microbank-customer:
    image: zacharyed/microbank-customer
    restart: on-failure
    ports:
      - "6010:6010"
  microbank-spring-cloud-config:
    image: zacharyed/microbank-spring-cloud-config
    ports:
      - "8888:8888"
  microbank-eureka:
    image: zacharyed/microbank-eureka
    ports:
      - "8761:8761"
  microbank-spring-cloud-gateway:
    image: zacharyed/microbank-spring-cloud-gateway
    ports:
      - "8765:8765"