spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://microbank-customer-service
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
---
server:
  port: 8765
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka